### ISSUE TITLE
Documentation: Include README's, with the following -->

### ISSUE THREAD

**Issue by jaemcu** [Team-Mongeese/bucket-list-client#5]
MUST INCLUDE: 
1.	 

- [ ] An explanation of the what the app does and how it works.
- [ ] 2.	 A link to the other repo (backend API on Github)
- [ ] 3.	 A link to both deployed sites
- [ ] 4.	 List of technologies used
- [ ] 5.	 List unsolved problems which would be fixed in future iterations.
- [ ] 6.	 Document your planning, process and problem-solving strategy
- [ ] 7.	 Complete the repository Description field and Website field with a meaningful sentence description of the application and link to the live URL  

Your front-end repo's README should also have:
1.	 Link to wireframes and user stories

**Comment by jaemcu** [comment]
- [ ] An explanation of the what the app does and how it works.
- [ ] A link to the other repo (backend API on Github)
- [ ] A link to both deployed sites
- [ ] List of technologies used
- [ ] List unsolved problems which would be fixed in future iterations.
- [ ] Document your planning, process and problem-solving strategy
- [X] Complete the repository Description field and Website field with a meaningful sentence description of the application and link to the live URL

Your front-end repo's README should also have:

- [ ] Link to wireframes and user stories

**Comment by BenLirio** [comment]
how did you make that?
